server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: servico-aluno
          uri: lb://servico-aluno
          predicates:
            - Path=/api/alunos/**
        - id: servico-professor
          uri: lb://servico-professor
          predicates:
            - Path=/api/professores/**
        - id: servico-disciplina
          uri: lb://servico-disciplina
          predicates:
            - Path=/api/disciplinas/**
        - id: servico-matricula
          uri: lb://servico-matricula
          predicates:
            - Path=/api/matriculas/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
